Fix typo
TypesettingTools/DependencyControl pull request #6
Opened 2017-03-26 00:57 UTC by CoffeeFlux

Introduced in
https://github.com/TypesettingTools/DependencyControl/commit/d469f38f2371f887f912efb32b3922e9140bd937
because I'm dumb and bad

2017-03-26 03:54 UTC, torque commented
thansk for this pull request, but im going to need to review your changse

2017-03-26 04:00 UTC, CoffeeFlux commented
thansk for this helpful comment, looking forward to your feedback

2017-03-26 16:56 UTC, torque requested changes
ive done some research and it appears this pull request is woefully incomplete. here is a list of typose iv foud (line: word):

4: managment
74: initalization
77: Cumlative
88: overriden
249: adverise
421: mininum
437: respecitively
543: depedencies
553: recursicely
557: extendend

pelase do better next tiem

There are also several references to `TypesettingCartel` that should be fixed.

2017-03-27 00:32 UTC, torque approved these changes

2017-04-07 19:02 UTC, merged